#!/usr/bin/perl

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;

use esmith::AccountsDB;
my $file = shift;
my $separator = shift;
my $accountsDb = esmith::AccountsDB->open() || die("Could not open accounts DB");

if($file) {
    open(FH, "<", $file) or die;
} else {
    open(FH, "-");
}

if( ! $separator) {
    $separator = "\t";
}

while(<FH>) {
    
    # Remove trailing whitespace:
    chomp $_;
    $_ =~ s/\s+$//;

    my ($groupname, $gid, $description, @members) = split(/$separator/, $_);

    if(defined getgrnam($groupname)) {
        warn "[WARNING] group $groupname exists. Skipped!\n";
        next;
    }

    my @missing_users = grep { ! getpwnam($_) } map { split(/,/, $_) } @members;
    if(@missing_users) {
        warn "[WARNING] group $groupname is missing members " . join(', ', @missing_users) . ". Skipped!\n";
        next;
    }

    $accountsDb->new_record($groupname, {
        'type' => 'group', 
        'Description' => $description, 
        'Gid' => ($gid > 0 ? $gid : ''), 
        'Members' => join(',', @members)}
    );
    
    warn "[NOTICE] imported group $groupname\n";
}
